//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/HeartBeatMessage.msg.
//

#ifndef __VEINS_HEARTBEATMESSAGE_M_H
#define __VEINS_HEARTBEATMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/HeartBeatMessage.msg:27</tt> by nedtool.
 * <pre>
 * packet HeartBeatMessage extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1;
 *     string messageID;
 *     int serial = 0;
 *     int receipeintID;
 *     int senderID;
 *     Coord position;
 * }
 * </pre>
 */
class VEINS_API HeartBeatMessage : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress;
    ::omnetpp::opp_string messageID;
    int serial;
    int receipeintID;
    int senderID;
    Coord position;

  private:
    void copy(const HeartBeatMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HeartBeatMessage&);

  public:
    HeartBeatMessage(const char *name=nullptr, short kind=0);
    HeartBeatMessage(const HeartBeatMessage& other);
    virtual ~HeartBeatMessage();
    HeartBeatMessage& operator=(const HeartBeatMessage& other);
    virtual HeartBeatMessage *dup() const override {return new HeartBeatMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<HeartBeatMessage*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual const char * getMessageID() const;
    virtual void setMessageID(const char * messageID);
    virtual int getSerial() const;
    virtual void setSerial(int serial);
    virtual int getReceipeintID() const;
    virtual void setReceipeintID(int receipeintID);
    virtual int getSenderID() const;
    virtual void setSenderID(int senderID);
    virtual Coord& getPosition();
    virtual const Coord& getPosition() const {return const_cast<HeartBeatMessage*>(this)->getPosition();}
    virtual void setPosition(const Coord& position);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HeartBeatMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HeartBeatMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_HEARTBEATMESSAGE_M_H

